AWSTemplateFormatVersion: "2010-09-09"
Description: "EMR IAM Roles"

Resources:
  EMRDefaultRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EMR_DefaultRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "elasticmapreduce.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole"

  EMREC2DefaultRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EMR_EC2_DefaultRole"
      Description: "Allows EC2 instances in an EMR cluster to access other AWS services such as S3."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role"

  EMREC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: "EMR_EC2_DefaultRole"
      Path: /
      Roles:
        - !Ref EMREC2DefaultRole